name: 'Validate Artifacts'
description: 'Validates CloudFormation or Terraform Templates for security issues and quality'
author: '@rosswickman'
inputs:
  cft-dir:
    description: 'directory of templates to be delivered'
    required: true
runs:
  using: "composite"
  steps: 
    - run: echo Running CFN-NAG on templates
      shell: bash
    - run: echo Running Checkov on templates
      shell: bash
#     - run: |
#         apk add ruby-webrick
#         gem install cfn-nag
#         cfn_nag_scan --input-path ${{inputs.cft-dir}}
#       shell: bash
    
