---
name: 'Deploy Stackset'
description: ''
author: '@rosswickman'
runs:
  using: "composite"
  steps: 
    - run: |
        #cd src
        #chmod +rx *.ps1
        ./$GITHUB_ACTION_PATH/Start-MCMStackSetOperations.ps1 deploy
      shell: pwsh
