---
name: 'Deploy Stackset'
description: ''
author: '@rosswickman'
runs:
  using: "composite"
  steps: 
    - run: |
        cd src
        chmod +rx *.ps1
        ./Start-MCMStackSetOperations.ps1 deploy
      shell: pwsh
